music-app-master/music app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('music.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music-app-master/music/urls.py
from django.urls import path
from . import views

# app_name: For music application. Makes clear to user to which app he/she is working on.
app_name = 'music'
urlpatterns = [
    path('', views.publicsongs,name='publicsongs'),
    path('index', views.IndexView.as_view(), name='album_list'),
    path('register/', views.register, name='register'),
    path('login_user/', views.LoginView.as_view(), name='login_user'),
    path('logout_user/', views.LogoutView.as_view(), name='logout_user'),
    # /music/71/
    path('<int:pk>/', views.AlbumDetail.as_view(), name='detail'),
    path(r'songs/(?P<filter_by>[a-zA_Z]+)/', views.songs, name='songs'),
    # /music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name='create_album'),
    # /music/album/1
    path(r'album/<int:pk>/', views.AlbumUpdate.as_view(), name='update_album'),
    # /music/<album_id>/create_song/
    path('<int:album_id>/create_song/', views.create_song, name='create_song'),
    # /music/<int:album_id>/delete_song/<int:song_id>/
    path('<int:album_id>/delete_song/<int:song_id>/', views.delete_song, name='delete_song'),
    # /music/album/2/delete/
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='delete_album'),
    path('publicsongs', views.publicsongs),
    path('publicalbums', views.publicalbum),
]

music-app-master/music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.urls import reverse

type=(
    ('ty1','public'),
    ('ty2','private'),)
class Album(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    album_title = models.CharField(max_length=250)
    artist = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=1000)
    type=models.CharField(max_length=50,choices=type, default='public')
    


    # Returns album title along with artist for particular album.
    def __str__(self):
        return self.album_title + ' - ' + self.artist

    def get_absolute_url(self):
        return reverse('music:album_list')


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    type=models.CharField(max_length=50,choices=type, default='public')
    # Returns song title from Song model.
    def __str__(self):
        return self.song_title


    def get_absolute_url(self):
        return reverse('music:detail', args=[str(self.id)])

music-app-master/music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Album, Song

# *
# [AlbumForm]: Form for Album creation.


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo','type']

# *
# [UserForm]: Form for User signup.


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)  # Display password

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

# *
# [SongForm]: Form for song creation.


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file','type']

music-app-master/music/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.db.models import Q
from django.urls import reverse_lazy
from .models import Album, Song
from .forms import AlbumForm, UserForm, SongForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# *
# Index Function is used render index page that the user views.
# Is_authenticated: Is used to to authenticate the user and if he is not, then render to Login Page again.
# albums: Returns a new QuerySet containing objects that match the given lookup parameters. (With the help of filter)
# songs: Retreiving all the objects in the database.
# query: Search at index page has access to the q value in request.GET. Hence show results accordingly
#


class IndexView(LoginRequiredMixin, ListView):
    login_url = 'login_user/'
    redirect_field_name = 'redirect_to'
    model = Album
    template_name = 'music/album_list.html'
    context_object_name = 'albums'

    ''' get_queryset: Get the list of items for this view '''
    def get_queryset(self):
        return Album.objects.filter(user = self.request.user) 

def index(request):
     if not request.user.is_authenticated:
         return render(request, 'music/login.html')
     else:
         albums = Album.objects.filter(user=request.user)
         song_results = Song.objects.all()
         query = request.GET.get("q")
         if query:
             albums = albums.filter(Q(album_title__icontains=query) | Q(artist__icontains=query)).distinct()
             song_results = song_results.filter(Q(song_title__icontains=query)).distinct()
             return render(request, 'music/publicsongs.html', {
                 'albums': albums,
                 'songs': song_results,
             })
         else:
             return render(request, 'music/publicsongs.html', {'albums': albums})




    



class AlbumDetail(LoginRequiredMixin, DetailView):
    login_url = 'login_user/'
    redirect_field_name = 'redirect_to'
    model = Album
    template_name = 'music/detail.html'

    def detail(request, album_id):
        if not request.user.is_authenticated:
            return render(request, 'music/login.html')
        else:
            user = request.user
            album = get_object_or_404(Album, pk=album_id)
            return render(request, 'music/detail.html', {'album': album, 'user': user})


class AlbumCreate(LoginRequiredMixin, CreateView):
    login_url = 'login_user/'
    redirect_field_name = 'redirect_to'
    model = Album
    fields = ['album_title','artist','genre','album_logo']

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(AlbumCreate, self).form_valid(form)


class AlbumUpdate(LoginRequiredMixin, UpdateView):
    login_url = 'login_user/'
    redirect_field_name = 'redirect_to'
    model = Album
    fields = ['album_title','artist','genre','album_logo']

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(AlbumUpdate, self).form_valid(form)


    def create_album(request):
     if not request.user.is_authenticated:
         return render(request, 'music/login.html')
     else:
         form = AlbumForm(request.POST or None, request.FILES or None)
         if form.is_valid():
             album = form.save(commit=False)
             album.user = request.user
             album.album_logo = request.FILES['album_logo']
             file_type = album.album_logo.url.split('.')[-1]
             file_type = file_type.lower()
             if file_type not in IMAGE_FILE_TYPES:
                 context = {
                     'album': album,
                     'form': form,
                     'error_message': 'Image file must be PNG, JPG, or JPEG',
                 }
                 return render(request, 'music/create_album.html', context)
             album.save()
             return render(request, 'music/detail.html', {'album': album})
         context = {
             "form": form,
         }
         return render(request, 'music/create_album.html', context)



class AlbumDelete(LoginRequiredMixin, DeleteView):
    login_url = 'login_user/'
    redirect_field_name = 'redirect_to'
    model = Album
    success_url = reverse_lazy('music:album_list')

    def delete_album(request, album_id):
        album = Album.objects.get(pk=album_id)
        album.delete()
        albums = Album.objects.filter(user=request.user)
        return render(request, 'music/index.html', {'albums': albums})



def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/create_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'music/create_song.html', context)

        song.save()
        return render(request, 'music/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/create_song.html', context)




def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'album': album})






class LoginView(View):

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/album_list.html', {'albums': albums})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})


    def get(self, request):
        return render(request, 'music/login.html')

    def login_user(request):
     if request.method == "POST":
         username = request.POST['username']
         password = request.POST['password']
         user = authenticate(username=username, password=password)
         if user is not None:
             if user.is_active:
                 login(request, user)
                 albums = Album.objects.filter(user=request.user)
                 return render(request, 'music/index.html', {'albums': albums})
             else:
                 return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
         else:
             return render(request, 'music/login.html', {'error_message': 'Invalid login'})
     return render(request, 'music/login.html')


class LogoutView(View):
	def get(self, request):
		logout(request)
		form = UserForm(request.POST or None)
		context = {
			"form": form,
		}
		return render(request, 'music/login.html', context)

def logout_user(request):
        logout(request)
        form = UserForm(request.POST or None)
        context = {
            "form": form,
        }
        return render(request, 'music/login.html', context)

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/album_list.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)



def songs(request, filter_by):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'q':
                users_songs = users_songs.filter(filter_by)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })


def publicsongs(request):
    songs=Song.objects.filter(type='ty1')
    return render(request,'music/publicsongs.html',{'songs':songs})


def publicalbum(request):

music-app-master/music/templates/music/album_list.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo }}" alt = "Generic placeholder thumbnail" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:delete_album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_album' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music-app-master/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Vishnu{% endblock %}</title>
    <!-- Load static files -->
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="{% static 'music/js/jquery.min.js' %}"></script>
    <script src="{% static 'music/js/bootstrap.min.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" >Music by Vishnu</a>
        </div>

        <!-- Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <!-- For Albums Item -->
                <li class="">
                    <a href="{% url 'music:album_list' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <!-- For Songs Item -->
                <li class="">
                    <a href="{% url 'music:songs' 'all' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>
            <!-- For Search Item -->
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:album_list' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <!-- For Add Album Item -->
                <li>
                    <a href="{% url 'music:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <!-- For Logout Item -->
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music-app-master/music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Vishnu{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" >Music By Vishnu</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music-app-master/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{% block body %}

<div class="container-fluid songs-container">
    <div class="row">


        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo}}" alt = "Generic placeholder thumbnail" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>

                    <h1>{{ album.album_title }}<br><small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>


        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    <!-- For Error Message -->
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music-app-master/music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music-app-master/music/templates/music/login.html
{% extends 'music/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                          {% if error_message %}
                              <p><strong>{{ error_message }}</strong></p>
                          {% endif %}
                        <form id="loginform" class="form-horizontal" role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="form-group">
                              <label class="control-label col-sm-2" for="id_username">
                                  Username:
                              </label>
                              <div class="col-sm-10">
                                  <input id="id_username" maxlength="30" name="username" type="text">
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="control-label col-sm-2" for="id_password">
                                  Password:
                              </label>
                              <div class="col-sm-10">
                                  <input id="id_password" maxlength="30" name="password" type="password">
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <button type="submit" class="btn btn-success">Submit</button>
                              </div>
                          </div>
                          <div class="panel-footer">
                              Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                          </div>
                            </form>
                        </div>
                    </div>
        </div>
    </div>

<!-- <div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'music:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div> -->

{% endblock %}